# Generated by Django 4.0.6 on 2022-11-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasim', '0002_registration_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
