# Generated by Django 4.0.6 on 2022-11-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasim', '0004_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='product_category',
        ),
    ]
