# Generated by Django 4.0.6 on 2022-11-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasim', '0006_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.ImageField(default='', upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
