# Generated by Django 4.0.6 on 2022-11-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasim', '0008_rename_photo_registration_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AlterField(
            model_name='registration',
            name='img',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
