# Generated by Django 4.0.6 on 2022-11-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasim', '0009_staff_alter_registration_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
